CREATE DATABASE `Chores` /*!40100 DEFAULT CHARACTER SET latin1 */ /*!80016 DEFAULT ENCRYPTION='N' */;
Use Chores;
CREATE TABLE `Task` (`id` int(11) NOT NULL AUTO_INCREMENT, `name` varchar(50) NOT NULL DEFAULT 'task', PRIMARY KEY (`id`), UNIQUE KEY `id_UNIQUE` (`id`)) ENGINE=InnoDB AUTO_INCREMENT=41 DEFAULT CHARSET=latin1;
CREATE TABLE `Task_Events` ( `id` int(11) NOT NULL AUTO_INCREMENT, `Task_ID` int(11) NOT NULL, `Time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (`id`), KEY `id_idx` (`Task_ID`), CONSTRAINT `id` FOREIGN KEY (`Task_ID`) REFERENCES `Task` (`id`) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB AUTO_INCREMENT=1619 DEFAULT CHARSET=latin1;


DROP TRIGGER IF EXISTS `Chores`.`Task_AFTER_INSERT`;

DELIMITER $$
USE `Chores`$$
CREATE DEFINER = CURRENT_USER TRIGGER `Chores`.`Task_AFTER_INSERT` AFTER INSERT ON `Task` FOR EACH ROW
BEGIN
	INSERT INTO Task_Events ( Task_ID ) VALUES (NEW.id);
END$$
DELIMITER ;
